/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        "courierPrime": ["Courier Prime", "monospace"],
      }
    },
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        botanical: {  
          "primary": "#3E5D58",
          "secondary": "#DDE5ED",
          "accent": "#92ACA0",
          "neutral": "#3E5D58",
          "base-100": "#DDE5ED",
          "info": "#92ACA0",
          "success": "#92ACA0",
          "warning": "#92ACA0",
          "error": "#92ACA0",
          "primary-content": "DDE5ED",
          "secondary-content": "3E5D58",
          },
        oblivion: {
          "primary": "#474747",  
          "secondary": "#606a6b",
          "accent": "#ae98c7",
          "neutral": "#474747",
          "base-100": "#e3ddd1",
          "info": "#018bba",
          "success": "#77c33d",
          "warning": "#ffad01",
          "error": "#ff4222",
          "primary-content": "#e3ddd1",
          "secondary-content": "#474747",
          },
        nimbus: {
          "primary": "#f5f5f5",
          "secondary": "#b6e0ee",
          "accent": "#4b4d4c",
          "neutral": "#4b4d4c",
          "base-100": "#4b4d4c",
          "info": "#4b4d4c",
          "success": "#4b4d4c",
          "warning": "#4b4d4c",
          "error": "#4b4d4c",
          "primary-content": "#4b4d4c",
          "secondary-content": "#4b4d4c",
          },
        olivia: {
          "primary": "#2b2b2b",
          "secondary": "#e1dbd1",
          "accent": "#2b2b2b",
          "neutral": "#2b2b2b",
          "base-100": "#2b2b2b",
          "info": "#2b2b2b",
          "success": "#2b2b2b",
          "warning": "#2b2b2b",
          "error": "#2b2b2b",
          "primary-content": "#f1beb0",
          "secondary-content": "#2b2b2b",
          },
        delta: {
          "primary": "#111111",
          "secondary": "#e0e1e3",
          "accent": "#62d1be",
          "neutral": "#111111",
          "base-100": "#e0e1e3",
          "info": "#2b2b2b",
          "success": "#2b2b2b",
          "warning": "#2b2b2b",
          "error": "#2b2b2b",
          "primary-content": "#62d1be",
          "secondary-content": "#111111",
          },
        mizu: {
          "primary": "#243746",
          "secondary": "#b7d8eb",
          "accent": "#f8f7f3",
          "neutral": "#243746",
          "base-100": "#e0e1e3",
          "info": "#2b2b2b",
          "success": "#2b2b2b",
          "warning": "#2b2b2b",
          "error": "#2b2b2b",
          "primary-content": "#f8f7f3",
          "secondary-content": "#111111",
          },
        },
      ],
    },
}

